Repository kubeshop/botkube-docs, pull requests merged in 2022-10, with the labels that each got.

#156 Document priv channels in Slack
  docs/installation/socketslack/index.md
  src/css/custom.scss
  versioned_docs/version-0.14/installation/socketslack/index.md
Labels: enhancement

#161 Reorganize Usage docs and describe actionable notifications
  docs/configuration/communication/index.md
  docs/configuration/communication/vault-csi.md
  docs/configuration/executor.md
  docs/configuration/filter.md
  docs/configuration/helm-chart-parameters.md
  docs/configuration/source.md
  docs/examples/index.md
  docs/installation/discord/index.md
  docs/installation/elasticsearch/index.md
  docs/installation/index.mdx
  docs/installation/mattermost/index.md
  docs/installation/slack/index.md
  docs/installation/socketslack/index.md
  docs/installation/teams/index.md
  docs/installation/webhook/index.md
  docs/usage/assets/actionable-notifications.png
  docs/usage/assets/long-notification.png
  docs/usage/assets/short-notification.png
  docs/usage/event-notifications.md
  docs/usage/executing-commands.md
  docs/usage/filters/assets/filters_disable.png
  docs/usage/filters/assets/filters_enable.png
  docs/usage/filters/assets/filters_list.png
  docs/usage/filters/assets/tag_filter_sh.png
  docs/usage/filters/development.md
  docs/usage/filters/index.md
  docs/usage/index.md
  versioned_docs/version-0.13/usage/index.md
  versioned_docs/version-0.14/usage/index.md
Labels: enhancement

#163 Document the `kubectl` command builder
  docs/usage/assets/kc-cmd-builder.png
  docs/usage/executing-commands.md
Labels: enhancement

#164 interactive output filtering
  docs/usage/assets/output-filtering-filter-response.png
  docs/usage/assets/output-filtering-get-pods-metrics.png
  docs/usage/assets/output-filtering-get-pods.png
  docs/usage/assets/output-filtering-logs-response.png
  docs/usage/assets/output-filtering-metrics-logs-filter.png
  docs/usage/assets/output-filtering-metrics-logs.png
  docs/usage/filters/index.md
  docs/usage/interactive-output-filtering.md
Labels: enhancement

#166 version update during release
  .github/workflows/release.yml
  magefiles/target/sync-chart-md.go
Labels: enhancement

#158 Configure docs for the new marketing website
  community/contribute/elasticsearch-develop.md
  community/contribute/index.md
  community/contribute/ms-teams-develop.md
  community/contribute/webhook-develop.md
  docs/installation/index.mdx
  docs/usage/filters/development.md
  docusaurus.config.js
  redirects.js
  src/components/BotKubeFeatures/index.module.scss
  src/components/BotKubeFeatures/index.tsx
  src/components/Hero/index.module.scss
  src/components/Hero/index.tsx
  src/pages/index.module.scss
  src/pages/index.tsx
  src/pages/privacy/index.md
  src/plugins/contributors/index.js
  versioned_docs/version-0.13/filters/index.md
  versioned_docs/version-0.13/installation/index.mdx
  versioned_docs/version-0.14/installation/index.mdx
  versioned_docs/version-0.15/installation/index.mdx
  versioned_docs/version-0.15/usage/filters/development.md
Labels: enhancement, hold/do-not-merge

#170 Add installation redirection for docs
  redirects.js
Labels: bug
