Repository kubeshop/botkube-docs, pull requests merged in 2022-07, with the labels that each got.

#86 Update Helm chart uninstall command
  content/installation/Discord/_index.md
  content/installation/ElasticSearch/_index.md
  content/installation/Mattermost/_index.md
  content/installation/Slack/_index.md
  content/installation/Teams/_index.md
  content/installation/Webhook/_index.md
Labels: bug

#54 Add margin between icons and titles on homepage
  content/_index.md
Labels: enhancement

#87 Rename https://www.botkube.io to https://botkube.io
  README.md
  config.toml
  content/configuration/helm-options.md
  content/contribute/_index.md
  content/installation/Discord/_index.md
Labels: enhancement

#89 Update Google Analytics
  layouts/partials/custom-footer.html
  layouts/partials/header.html
Labels: enhancement

#90 Add Cookie policy and website disclaimer
  .gitignore
  config.toml
  content/privacy.md
  layouts/partials/header.html
Labels: enhancement

#92 Add dead link CI checker
  .github/workflows/periodic-checks.yaml
  .mlc.config.json
  README.md
  content/contribute/_index.md
  content/filters/_index.md
  content/installation/_index.md
  content/privacy.md
  hack/check-links.sh
  netlify.toml
Labels: enhancement

#94 Update local development guide
  content/contribute/_index.md
Labels: enhancement

#95 Add CODEOWENRS, SECURITY.md, CONTRIBUTING.md, tmpls and update README.md
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: enhancement

#97 Run the dead link checker on PR, run against local server
  .github/workflows/dead-link-checker.yaml
  .github/workflows/periodic-checks.yaml
  .mlc.config.json
  README.md
  content/configuration/communication/vault-csi.md
  hack/check-links.sh
Labels: enhancement, hold/do-not-merge

#101 Describe events collection details in Privacy Policy
  content/privacy.md
Labels: enhancement

#99 Add make target to sync Helm Chart parameters
  CONTRIBUTING.md
  content/configuration/helm-chart-parameters.md
  magefiles/README.md
  magefiles/go.mod
  magefiles/go.sum
  magefiles/helm/sync-chart-md.go
  magefiles/magefile.go
  magefiles/printer/printer.go
Labels: enhancement, hold/do-not-merge

#102 Update configuration related docs
  content/configuration/_index.md
  content/configuration/communication/_index.md
  content/configuration/global.md
  content/configuration/helm-chart-parameters.md
  content/configuration/resource.md
  content/contribute/_index.md
  content/examples/_index.md
  content/installation/Discord/_index.md
  content/installation/ElasticSearch/_index.md
  content/installation/Mattermost/_index.md
  content/installation/Slack/_index.md
  content/installation/Teams/_index.md
  content/installation/Webhook/_index.md
  content/usage/_index.md
Labels: enhancement

#103 Mention ability to set custom MS Teams bot username
  content/configuration/communication/_index.md
  content/installation/Teams/_index.md
Labels: enhancement

#105 Migrate check-links.sh to Go
  .github/workflows/dead-link-checker.yaml
  hack/check-links.sh
  magefiles/go.mod
  magefiles/go.sum
  magefiles/magefile.go
  magefiles/printer/printer.go
  magefiles/shellx/async-cmd.go
  magefiles/shellx/cmd.go
  magefiles/target/dead-link.go
  magefiles/target/sync-chart-md.go
Labels: enhancement

#108 Update notifier commands documentation
  content/usage/_index.md
  static/images/notifier-start.png
  static/images/notifier-status.png
  static/images/notifier-stop.png
  static/images/notifier_start.png
  static/images/notifier_status.png
  static/images/notifier_stop.png
Labels: enhancement
