Repository kubeshop/botkube-docs, pull requests merged in 2023-07, with the labels that each got.

#241 Use botkube install, fix sync:cli, remove certs flag from MM
  docs/cli/commands/botkube.md
  docs/cli/commands/botkube_install.md
  docs/cli/commands/botkube_login.md
  docs/cli/commands/botkube_migrate.md
  docs/cli/commands/botkube_uninstall.md
  docs/cli/commands/botkube_version.md
  docs/cli/getting-started.mdx
  docs/configuration/executor/doctor.md
  docs/configuration/executor/exec.md
  docs/configuration/executor/helm.md
  docs/configuration/executor/kubectl.md
  docs/configuration/general.md
  docs/configuration/index.mdx
  docs/configuration/source/kubernetes.md
  docs/configuration/source/prometheus.md
  docs/installation/discord/index.md
  docs/installation/elasticsearch/index.md
  docs/installation/index.mdx
  docs/installation/mattermost/index.md
  docs/installation/slack/index.md
  docs/installation/teams/index.md
  docs/installation/webhook/index.md
  docs/usage/event-notifications.md
  magefiles/target/sync-cli-docs.go
Labels: bug, enhancement

#242 Fix CLI download URL syntax
  docs/cli/getting-started.mdx
Labels: bug

#243 Unify installation tabs for CLI
  docs/cli/getting-started.mdx
  docs/configuration/helm-chart-parameters.md
Labels: enhancement

#244 Fix validating release target
  magefiles/target/release.go
Labels: bug

#249 Update getting-started.mdx added a comment for the linux users.
  docs/cli/getting-started.mdx
Labels: enhancement

#251 Add new `reactions:write` scope
  docs/installation/slack/index.md
Labels: enhancement
